kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.name }}
spec:
  port:
    targetPort: {{ .Values.route.targetPort }}
  tls:
    termination: {{ .Values.route.termination }}
  to:
    kind: {{ .Values.route.kind }}
    name: {{ .Values.name }}
    weight: {{ .Values.route.weight }}