{{ if .Values.artifactorysecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Files.Get ".dockerconfigjson" | b64enc | quote }}
{{ end }}