apiVersion: v1
kind: Secret
metadata:
  name: db-config-secret
data:
  user: {{ .Values.dbConfigSecret.user | b64enc | quote }}
  name: {{ .Values.dbConfigSecret.name | b64enc | quote }}
  password: {{ .Values.dbConfigSecret.password | toString | b64enc | quote }} 
